### ISSUE TITLE
Compartment names should be parameterizable

### ISSUE THREAD

**Issue by shntnu** [cytomining/pycytominer#110]
It's possible this is already the case, but @pamzgt wasn't able to find it

**Comment by gwaygenomics** [comment]
the default is ["cells", "cytoplasm", and "nuclei"], but compartments are indeed parameterizable: https://github.com/cytomining/pycytominer/blob/master/pycytominer/aggregate.py#L30

It is possible they are not parameterized somewhere, but if so, we should rectify.

**Comment by gwaygenomics** [comment]
ah, I just realized that pycytominer will throw an error for non-canonical compartments: https://github.com/cytomining/pycytominer/blob/ac3ef680c1f4625aa1e8452b431afb5af8bcdd41/pycytominer/cyto_utils/util.py#L15

We should probably update this to throw a warning instead.

**Comment by pamzgt** [comment]
My bad. I was taking a very quick look and did not realize that  <compartments> referred to the table names in the sqlite file.

**Comment by pamzgt** [comment]
To give a bit of context, I was trying to feed an sqlite db with the following tables:  'Per_Image', 'Per_Cells', 'Per_Cytoplasm', 'Per_Nuclei'.

passing `compartments =["Per_Cells", "Per_Cytoplasm", "Per_Nuclei"]` results in an `error: compartment not supported, use one of ['cells', 'cytoplasm', 'nuclei'].` Also, the image table should be called Image and can not be parameterized.  

At the moment, I did not know about [cytominer-database](https://github.com/cytomining/cytominer-database). But I guess that it was created to fix these issues :)

**Comment by shntnu** [comment]
@pamzgt `cytominer-database` will use the same as your CSV files for the corresponding tables. So if your CSV files are called `Per_Cells.csv`, the table will be called `Per_cells` (if you use the latest version, because of this [line](https://github.com/cytomining/cytominer-database/blob/9cf43400a01b82e4b4bce0901e039b7f24519ffe/cytominer_database/ingest.py#L174)). 

But the fix is simple!

```sh
sqlite3 backend.sqlite 'alter table Per_cells rename to Cells'
```

See https://sqlite.org/lang_altertable.html

**Comment by gwaygenomics** [comment]
update: I needed to solve this in #111 - working on it now

**Comment by gwaygenomics** [comment]
turns out that the "good first issue" tag here was wrong 😂 

Long story short, this is now fully modular (and fully tested) in #111 

One key block preventing an easy fix is [here](https://github.com/cytomining/pycytominer/pull/111/commits/f9adf9407f587519f6479bf875fe722be65799c6#diff-ed9097fc5b9747e8287afce4ba63d18724e3e88d7725fabda9b28be2e6ab81f2R475-R487)

This is now implemented:

```python

from pycytominer.cyto_utils.cells import SingleCells

# Only SQLite supported currently
sc = SingleCells(file_or_conn="sqlite:///EXAMPLE_PATH.sqlite")

# Merge single cell data using the appropriate linking columns
# Linking columns can also be specified for modular compartments
# Different normalization methods also available (see normalize.py)
sc_df = sc.merge_single_cells(single_cell_normalize=False)

# For the default linking cols and for specific modular formatting, run the following
from pycytominer.cyto_utils import get_default_linking_cols
get_default_linking_cols()

## Aggregate single cells
level_3_df = sc.aggregate_profiles()

## Note that above is equivalent to:
from pycytominer import aggregate
level_3_df = aggregate(sc_df)
```
