### ISSUE TITLE
Test Spherize more extensively

### ISSUE THREAD

**Issue by shntnu** [cytomining/pycytominer#127]
`Spherize` only tests for the default `epsilon`

https://github.com/cytomining/pycytominer/blob/dfd355d748f80c658a85720e9c9bfde7ce58c02c/pycytominer/tests/test_operations/test_transform.py#L21-L40

**Comment by shntnu** [comment]
Hm – actually I don't think the test is actually working
https://colab.research.google.com/drive/1KitZF-CgV_xgZpd1n0BieQpko-uD4ZQA?usp=sharing

**Comment by gwaygenomics** [comment]
i don't have any idea what that collab notebook means!

@shntnu - this is quickly becoming a pretty critical piece in the lincs cell painting dataset. I'd like to solve it once and for all. see broadinstitute/lincs-cell-painting#60.

Does the notebook mean the test needs to be fixed? Or that the test is showing that the spherize function is incorrect in some way? Does the notebook propose a new test?

**Comment by gwaygenomics** [comment]
In #132, I added a `spherize_epsilon` parameter. When we close this issue, we can address this variable here as well.

**Comment by shntnu** [comment]
Sorry for leaving this stray comment without an explanation :D 

The notebook shows that this (covariance) matrix will pass the test even though it is not spherized.

![image](https://user-images.githubusercontent.com/1210428/111653532-62805880-87de-11eb-8839-7b2bc6b5b8ad.png)

But as we discussed, you needn't do more here. The code looks right!

**Comment by shntnu** [comment]
Oh I just noticed this https://github.com/cytomining/pycytominer/issues/127#issuecomment-801467132

nvm – feel free to reopen or use a new issue, as you see fit @gwaygenomics
