### ISSUE TITLE
aggregate will drop samples with missing values

### ISSUE THREAD

**Issue by gwaygenomics** [cytomining/pycytominer#133]
if the columns in `strata` contain missing values, aggregate will drop the sample! This is a bug, that thankfully has an easy fix.

We need to add `dropna=False` to: https://github.com/cytomining/pycytominer/blob/d78630939ac4ae0960df4d6dfd001687ff11600b/pycytominer/aggregate.py#L65-L66

**Comment by shntnu** [comment]
Yikes, bad choice for default behavior (in pandas). Glad you caught it.
