### ISSUE TITLE
Suggestion to add figure to README

### ISSUE THREAD

**Issue by dlogan** [cytomining/pycytominer#141]
I think this high-level figure (of yours, @gwaygenomics !) would be useful to the newcomer, say at the top of the README docs: 
 
![pycytominer_workflow](https://user-images.githubusercontent.com/1225595/116783552-44ed1280-aa5d-11eb-8d5c-3b7b64775bc9.png)

The same would go for the Docs here: https://pycytominer.readthedocs.io/en/latest/

**Comment by gwaygenomics** [comment]
Great idea - thanks @dlogan !
