### ISSUE TITLE
Modz function giving an unknown error 

### ISSUE THREAD

**Issue by MerajRamezani** [cytomining/pycytominer#165]
I am trying to use modz function for aggregating plate level data after normalization and feature selection. The input Dataframe has 2 MetaData columns and 589 features without any NA. I am currently using the pooled-cell-painting-analysis environment (from the pooled-cell-painting-data-analysis repo on github with pandas version 1.2) and here is the code:

`dmem_modz_df= modz(
                    population_df=dmem_feature_selected_df, 
                    replicate_columns=['Metadata_Foci_Barcode_MatchedTo_GeneCode' ,'Metadata_Foci_Barcode_MatchedTo_Barcode'], 
                    features='infer', 
                    method='spearman', 
                    precision=5)
`

And here is the error message:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-814dffb31fab> in <module>
      4                     features='infer',
      5                     method='spearman',
----> 6                     precision=5)
      7 
      8 dmem_modz_df

~\.conda\envs\pooled-cell-painting-analysis\lib\site-packages\pycytominer\cyto_utils\modz.py in modz(population_df, replicate_columns, features, method, min_weight, precision)
    111         population_df.groupby(replicate_columns)
    112         .apply(
--> 113             lambda x: modz_base(
    114                 x.loc[:, features],
    115                 method=method,

~\.conda\envs\pooled-cell-painting-analysis\lib\site-packages\pandas\core\groupby\groupby.py in apply(self, func, *args, **kwargs)
    892         with option_context("mode.chained_assignment", None):
    893             try:
--> 894                 result = self._python_apply_general(f, self._selected_obj)
    895             except TypeError:
    896                 # gh-20949

~\.conda\envs\pooled-cell-painting-analysis\lib\site-packages\pandas\core\groupby\groupby.py in _python_apply_general(self, f, data)
    929 
    930         return self._wrap_applied_output(
--> 931             keys, values, not_indexed_same=mutated or self.mutated
    932         )
    933 

~\.conda\envs\pooled-cell-painting-analysis\lib\site-packages\pandas\core\groupby\generic.py in _wrap_applied_output(self, keys, values, not_indexed_same)
   1201             # values are Series
   1202             return self._wrap_applied_output_series(
-> 1203                 keys, values, not_indexed_same, first_not_none, key_index
   1204             )
   1205 

~\.conda\envs\pooled-cell-painting-analysis\lib\site-packages\pandas\core\groupby\generic.py in _wrap_applied_output_series(self, keys, values, not_indexed_same, first_not_none, key_index)
   1254         # Combine values
   1255         # vstack+constructor is faster than concat and handles MI-columns
-> 1256         stacked_values = np.vstack([np.asarray(v) for v in values])
   1257 
   1258         if self.axis == 0:

<__array_function__ internals> in vstack(*args, **kwargs)

~\.conda\envs\pooled-cell-painting-analysis\lib\site-packages\numpy\core\shape_base.py in vstack(tup)
    280     if not isinstance(arrs, list):
    281         arrs = [arrs]
--> 282     return _nx.concatenate(arrs, 0)
    283 
    284 

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 589 and the array at index 2472 has size 1

**Comment by MerajRamezani** [comment]
@bethac07 @gwaygenomics Here is what I got from the function when I only selected top 200 rows of the df as input:

<img width="1792" alt="Screen Shot 2021-09-07 at 5 16 07 PM" src="https://user-images.githubusercontent.com/85960354/132415673-1db2cd70-132b-4ed9-880c-c35803bc0839.png">

**Comment by MerajRamezani** [comment]
And here is the modz function actual code:

https://github.com/cytomining/pycytominer/blob/master/pycytominer/cyto_utils/modz.py

**Comment by MerajRamezani** [comment]
Great @bethac07 it seems like you have nailed down the issue. If I aggregate to gene level using modz it goes without a hitch, which kind of confirm your argument! Is it possible for you to share the fix here so I can use it in my code right away?

**Comment by bethac07** [comment]
@MerajRamezani  https://github.com/cytomining/pycytominer/pull/166
