### ISSUE TITLE
Add normalization option to "regress" feature

### ISSUE THREAD

**Issue by gwaybio** [cytomining/pycytominer#169]
In the Rohban Lab's most recent preprint ([Rezvani et al.](https://www.biorxiv.org/content/10.1101/2021.09.09.459624v1)), the authors performed a nifty analysis showing that signal for predicting compound MOA improves if one first regresses out the influence of Cell Area on other CellProfiler features (Figure 2 of their paper). 

The authors also nicely include their code for doing so ([link here](https://github.com/rohban-lab/Data-Cleaning-for-image-based-profiling-Enhancement/blob/8edd3ffe6741f0141c9d73c9c8d172f493caff34/final_find_representation.py#L60-L70)).

We should consider adding this functionality as an enhancement to pycytominer!

**Comment by gwaygenomics** [comment]
We could easily generalize this functionality to regress any feature (or multiple features) as well

**Comment by gwaybio** [comment]
Not pursuing this for now. Feel free to re-open if we decide to implement in the future.
