### ISSUE TITLE
New community members

### ISSUE THREAD

**Issue by gwaybio** [cytomining/pycytominer#178]
Hi everyone! 👋 

It's my pleasure to introduce @staylorx and @falquaddoomi to our cytomining community. Steve and Faisal will be contributing their software engineering expertise to several packages in our ecosystem including `pycytominer`, `DeepProfiler`, and `cytominer-eval`. Faisal has DevOps experience, so we may bleed our efforts into the `profiling-recipe` and begin initiatives on a more general `weld` codebase as well.

A bit of background on the duo, so that we're not strangers when we interact in the coming months :)

## Steve Taylor

@staylorx is the Software Engineering Team Manager for the Center for Health Artificial Intelligence. Steve has over 20 years of public, private, and government experience in management and software development. Before joining the University of Colorado, Steve’s career centered on integration: hardware with industrial electrical controls, software with IT business systems, and eventually both, in what has become big data and the Internet of Things.

Steve shares his love of learning and technology with others as a part-time lecturer, teaching programming, analytics, and visualization to undergraduates at the Leeds School of Business at the University of Colorado Boulder. 

He earned an MBA from the University of Colorado Executive Programs and a BS in Mathematics from Metropolitan State College of Denver. A private pilot, amateur radio operator, hobby mechanic, and inveterate tinker, Steve lives with his wife and daughter on the Colorado plains, north-east of Denver.

Steve, I didn't know you were a pilot! Lots of airspace and views here in Denver to play around.

## Faisal Alquaddoomi

@falquaddoomi has been working as a full-stack developer for the past fifteen years or so. He was the lead developer on [svip.ch](https://svip.ch/) (the swiss variant interpretation platform), a variant database with a curation interface (still in prototype mode!).

Prior and during that time, he worked with the brca challenge on [brca exchange](https://www.brcaexchange.org/), mostly as a mobile developer, but also on their web frontend and pipeline.

Since starting at the University of Colorado Anschutz Center for Health AI (CHAI) last July, he's been doing a lot of devops; He set up [tislab's](https://tislab.org/) [monarch stack on google cloud](https://monarchinitiative.org/), for instance, and he's been helping folks with various cloud deployment and distributed computing issues.

## Initiatives

For now, Steve and Faisal will be poking around the codebases and issues to get a feel for what we're about here. We'll use GitHub Projects to track milestones and deliverables, but, as these are fairly new codebases, the processes by which we make progress are also flexible. If something isn't working, let's change it!

Faisal and Steve, note that @niranjchandrasekaran and I are currently the co-maintainers of this repo. And see our [`CONTRIBUTING.md`](https://github.com/cytomining/pycytominer/blob/master/CONTRIBUTING.md) document to see some of our general policies.

I'm excited for this new chapter!

**Comment by niranjchandrasekaran** [comment]
Hi Steve and Faisal! Look forward to working together.
