### ISSUE TITLE
Address Pandas Dataframe Merge and Other Performance Issues

### ISSUE THREAD

**Issue by d33bs** [cytomining/pycytominer#199]
Pandas Dataframe merge (and likely other) performance during various runtime operations may hinder or completely stall progress. This issue is dedicated to addressing Pandas merge and other performance challenges, including solutions which may not involve or migrate from Pandas itself. 

Issues which may be related or tied to this:
- #195 
- #198

**Comment by gwaybio** [comment]
@d33bs - does #219 solve this issue? Can we close?

**Comment by d33bs** [comment]
Hi @gwaybio - I feel good about closing this issue given #219's solution. If there are other known areas where Pandas DataFrame merges are causing performance issues we could address those more specifically as they come up.
