### ISSUE TITLE
Add Automated Linting Check for Black Formatting

### ISSUE THREAD

**Issue by d33bs** [cytomining/pycytominer#200]
An automated linting check for [Black](https://github.com/psf/black) formatting would provide visibility into whether repo changes adhere standards mentioned in CONTRIBUTING.md. This lint check would fail if related code does not meet Black formatting standards.

This issue comes as the result of conversations within #195 .

**Comment by d33bs** [comment]
Merged with #208

**Comment by d33bs** [comment]
Reopening as the merge was with `develop`

**Comment by kenibrewer** [comment]
@d33bs I was browsing old issues for things that might interest me and I think this one can be closed.
