### ISSUE TITLE
Next pycytominer release

### ISSUE THREAD

**Issue by gwaybio** [cytomining/pycytominer#207]
In #160, several of us discussed a potential release strategy. I'll break out this discussion in a new issue, where we can continue a discussion

## Previous discussion

Another important note is that we may want to release a pycytominer version 0.1.5 prior to merging this contribution (this contribution can be pycytominer version 0.2), just to make sure pycytominer is completely up-to-date functionally, in an intermediate, but stable version.

I'll also loop in @d33bs about this decision point. Dave, does this release schedule sound like a reasonable strategy? (Beth, note that @d33bs's https://github.com/cytomining/pycytominer/pull/203 PR is to a develop branch, but his https://github.com/cytomining/pycytominer/pull/197 is to master.)

If the release strategy looks kosher, then we'll likely want to:

1.  ✅ merge #197
2. ✅ Release v0.1.5
3. ✅ merge #160
4. ✅ Release v0.2.0
5. ✅ Update conda package
    a. And resolve conda-forge/pycytominer-feedstock/issues/1 
7. Work on develop for future releases

**Comment by d33bs** [comment]
Thank you @gwaybio - sounds good to me! Small suggestion: If using a 3 number versioning (v.0.1.5) it may be beneficial to stick with that convention throughout for clarity (v0.2.0 instead of v0.2).

**Comment by gwaybio** [comment]
Working on step 5 ☝️ in conda-forge/pycytominer-feedstock#2

**Comment by gwaybio** [comment]
Released version 0.2.0 in https://github.com/cytomining/pycytominer/releases/tag/v0.2.0
