### ISSUE TITLE
cannot import noise_removal 

### ISSUE THREAD

**Issue by yhan8** [cytomining/pycytominer#239]
import `noise_removal `gives the following error. I can import every other functions within `operations` except `noise_removal`. 
![Screen Shot 2022-11-08 at 3 04 30 PM](https://user-images.githubusercontent.com/74940557/200664337-46eb15df-4391-43cf-8169-b0a880d15ee5.png)

*******************************************
<img width="687" alt="Screen Shot 2022-11-08 at 3 07 06 PM" src="https://user-images.githubusercontent.com/74940557/200664553-a18a2cfd-0d3d-440d-9711-9505ce320888.png">

**Comment by shntnu** [comment]
@yhan8 can you add a few more [notes](https://github.com/cytomining/pycytominer/blob/8e5d27f592b10b10a73c55b6335e30e1c6c492fd/CONTRIBUTING.md#bug-reporting)?

**Comment by yhan8** [comment]
The way I am installing `pycytominer` is through the command below in the environment file. 
```
- pip:
  - git+https://github.com/cytomining/pycytominer@388bc35cdc044da8f2bdcbd8edbfa2bf66cf1198
```
I've tried to import other functions within `operations` to test whether it is `noise_removal` problem alone or all functions. Turns out that I can import all other function within `operations`, except `noise_removal`. 

I don't have input data as I am just trying to import this function.

**Comment by shntnu** [comment]
Ah – that version of pycytominer didn't have `noise_removal` 🎉 
https://github.com/cytomining/pycytominer/tree/388bc35cdc044da8f2bdcbd8edbfa2bf66cf1198/pycytominer/operations

Got with the most recent version, unless there's a good reason not to do so.

**Comment by gwaybio** [comment]
Nice catch! @yhan8 - please let us know if @shntnu's solution works, and close this issue once you confirm. Thanks!!

**Comment by yhan8** [comment]
So I used the newest link in README below, and updated the environment, it still won't work. Any thoughts?

-```
 pip:
  - git+https://github.com/cytomining/pycytominer@2aa8638d7e505ab510f1d5282098dd59bb2cb470
```

**Comment by yhan8** [comment]
Thanks Greg! I am unclear on how this works though, so I googled [this step](https://stackoverflow.com/questions/49651207/how-can-i-create-a-github-permalink-to-a-line-in-a-markdown-md-or-rmd-file), and I am able to get to the blame view of the noise_removal function, and where do I press 'Y'?

**Comment by shntnu** [comment]
@yhan8 

- Go to https://github.com/cytomining/pycytominer
- Press y
- It will replace the URL to https://github.com/cytomining/pycytominer/tree/8e5d27f592b10b10a73c55b6335e30e1c6c492fd (as of today)
- 8e5d27f592b10b10a73c55b6335e30e1c6c492fd is what you need
