### ISSUE TITLE
Feature select operation `blocklist` confusion

### ISSUE THREAD

**Issue by jenna-tomkinson** [cytomining/pycytominer#274]
I am confused about how the `blocklist` operation works when performing feature selection.

I had assumed that blocklist was performing a function to find features to block, but now looking at the function, I see an optional parameter called `blocklist_file`. Based on the below code in [feature_select.py](https://github.com/cytomining/pycytominer/blob/a5ae6c81a275b692ef5d4c85cfeb37696bf69242/pycytominer/feature_select.py#L152):

```python
 elif op == "blocklist":
            if blocklist_file:
                exclude = get_blocklist_features(
                    population_df=profiles, blocklist_file=blocklist_file
                )
            else:
                exclude = get_blocklist_features(population_df=profiles)
```

It uses the `get_blocklist_features` function, but if the file isn't provided, it will not provide the file in the function.

But when I go to the [get_blocklist_features function](https://github.com/cytomining/pycytominer/blob/a5ae6c81a275b692ef5d4c85cfeb37696bf69242/pycytominer/cyto_utils/features.py#L13), I see that the `blocklist_file` is not an optional parameter and it is loaded in as the first line of code.

```python
def get_blocklist_features(blocklist_file=blocklist_file, population_df=None):
    """Get a list of blocklist features.

    Parameters
    ----------
    blocklist_file : path-like object
        Location of the dataframe with features to exclude.
    population_df : pandas.core.frame.DataFrame, optional
        Profile dataframe used to subset blocklist features.

    Returns
    -------
    blocklist_features : list of str
        Features to exclude from downstream analysis.
    """

    blocklist = pd.read_csv(blocklist_file)
```

I am now confused about why I do not receive an error, as not all the variables are provided to the function. 

In the documentation, it states for the `blocklist_file` variable:

> blocklist_file : str, optional
        File location of datafrmame with with features to exclude. Note that if "blocklist" in operation then will remove standard blocklist.

Does this mean that there is a standard file the function uses instead?

If someone could please explain how this operation works or what I am missing, I would really appreciate it!

Here is example code of what I am attempting to run:

```python
# list of operations for feature select function to use on input profile
feature_select_ops = [
    # create a list of exlcuded features that have very low varience of values between single cells
    "variance_threshold",
    # creates a list of features so that there are no features with a correlation to another greater
    # than the default thresohold (`threshold=0.9`).
    "correlation_threshold",
    # documentation TBD
    "blocklist",
]

# process each run
for plate, info in plate_info_dictionary.items():
    normalized_df = pd.read_parquet(info["normalized_path"])
    output_file = str(pathlib.Path(f"{output_dir}/{plate}_sc_norm_fs.parquet"))
    print(f"Performing feature selection on normalized annotated merged single cells for {plate}!")

    # perform feature selection with the operations specified
    feature_select_df = feature_select(
        normalized_df,
        operation=feature_select_ops,
        output_file="none",
    )
```

**Comment by d33bs** [comment]
Hi @jenna-tomkinson, thank you for reaching out! It looks like `get_blocklist_features` has [a default set for the blocklist_file](https://github.com/cytomining/pycytominer/blob/master/pycytominer/cyto_utils/features.py#L8) which I believe references [this file]( https://github.com/cytomining/pycytominer/blob/master/pycytominer/data/blocklist_features.txt). The code example you shared would I think result in this default being used for `blocklist` exclusions.

I hope this answers your question, but please don't hesitate to let us know if you have any further questions or if I may clarify. Happy cytomining!
