### ISSUE TITLE
[Refactor] Migrate from setuptools to pyproject.toml

### ISSUE THREAD

**Issue by kenibrewer** [cytomining/pycytominer#278]
A pyproject.toml file allows more standardized definition of dev, test, build, and run dependencies. It would also allow more granular configuration of tools such as black with configurable line width and other factors. 

Here is a good guide to setting up a pyproject.toml that I would recommend to anyone working on this issue: https://betterprogramming.pub/a-pyproject-toml-developers-cheat-sheet-5782801fb3ed

**Comment by gwaybio** [comment]
@kenibrewer - are you able to take this on? We'd like to have this for version 1

**Comment by kenibrewer** [comment]
@gwaybio What's the timeline for the version 1 release? I'll be pretty busy until June 24th, but will have some additional time to work on open-source projects after that.

**Comment by gwaybio** [comment]
We are aiming to release version 1 prior to paper submission (which we're planning concurrently, all pycytominer contributors will be authors). We're aiming paper submission in 4 months.

So after June 24 sounds great! (we'll likely want to release several months before paper sub, as a soft deadline)

**Comment by kenibrewer** [comment]
Sure. I can take this on. Feel free to assign this issue to me so I can keep track.

I've been looking at Python Poetry lately. Any objections if I use that as the build engine and for dependency management?

**Comment by gwaybio** [comment]
No objections! @d33bs has experience and will likely be happy to see this. Thanks!

**Comment by d33bs** [comment]
Cheers @kenibrewer - Poetry is a pleasure to work with and could offer enhancements to this project. Do you have any thoughts surrounding how core python `pyproject.toml` expectations may align with that of Poetry's format? My last recollection was that there may be inconsistencies to be aware of when moving towards Poetry (potentially minor, likely depending on the scenario), but maybe this has changed.

**Comment by gwaybio** [comment]
Checking in on this @kenibrewer - have you been able to find the time? This is the final feature prior to version 1 release! :)

(no worries if you haven't found time, we can prioritize this if need be - there is also no real rush, just eagerness on our part)
