### ISSUE TITLE
Inconsistent `unique_cut` default value in `variance_threshold` vs `feature_select`

### ISSUE THREAD

**Issue by alxndrkalinin** [cytomining/pycytominer#282]
I noticed that `variance_threshold` [always had](https://github.com/cytomining/pycytominer/blame/69f5953800cd3e7b5e2eb73447c8028c8660356c/pycytominer/variance_threshold.py#L7) `unique_cut=0.01` as a default, while `feature_select` [later set](https://github.com/cytomining/pycytominer/commit/50233cf4e2e0a586526c167764b75ebccdac82a9#diff-9663e5e233193c07b7da5bf152568cc107832af78e2e025eb3b803225d5c39feR25) more strict default `unique_cut=0.1`, overriding that of `variance_threshold`.

I'm wondering if this default change was a typo or had a reason and what default setting should suit most projects.

**Comment by gwaybio** [comment]
thanks @alxndrkalinin ! I think this is a typo. Feel free to file a PR to keep the default consistent. Most folks invoke `variance_threshold` through `feature_select()` so it's probably best to change the default in variance_threshold.

**Comment by alxndrkalinin** [comment]
@gwaybio here you go #283
