### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by vincerubinetti** [cytomining/pycytominer#299]
Touchup logo to make consistent with other logos:

![image](https://github.com/WayScience/CytoSnake/assets/8326331/ebdceadd-df09-4d7d-8546-04e6faf8a96e)

**Comment by gwaybio** [comment]
These look great! @vincerubinetti - as we just discussed, would you be able to quickly create a cytomining org logo? (perhaps just the plain cell without any front material like the table, snake or pickaxe)? Thanks!

**Comment by vincerubinetti** [comment]
General "Cytomining" logo:

[logo.zip](https://github.com/cytomining/pycytominer/files/11853519/logo.zip)

**Comment by gwaybio** [comment]
@vincerubinetti - are you able to file PRs into the respective repos adding the logos? (I'd love for you to get attribution directly)

If not, we can add ourselves
