### ISSUE TITLE
Remove `master` branch references after migrating to `main`

### ISSUE THREAD

**Issue by d33bs** [cytomining/pycytominer#318]
This issue highlights a need to remove remaining mentions of the `master` branch after migrating to use `main` instead. Some of the discussion on this topic occurred via https://github.com/cytomining/pycytominer/pull/303#discussion_r1283814743 . Both `master` and `main` were provided in the merged work found in #303 to help with this transition.

**Comment by kenibrewer** [comment]
@d33bs Could you please assign this one to me too?

**Comment by d33bs** [comment]
Thank you for the follow up on this @kenibrewer ! Assigning this to you now.
