### ISSUE TITLE
[Refactor] Migrate dependencies in docs/requirements.txt to pyproject.toml

### ISSUE THREAD

**Issue by kenibrewer** [cytomining/pycytominer#321]
As part of the migration to poetry for dependency management in pycytominer, we should migrate the dependencies listed in `docs/requirements.txt` to `pyproject.toml`. This includes the following tasks:

- [ ] For each dependency, run a command similar to `poetry add sphinx@~7.1 --group docs`
- [ ] Delete the `docs/requirements.txt` file
- [ ] Delete the lines in `readthedocs.yml` that install `docs/requirements.txt`
- [ ] Update the `poetry.lock` file

**Comment by kenibrewer** [comment]
@d33bs Could you assign this issue to me? I'd be happy to do this one.

**Comment by d33bs** [comment]
Hi @kenibrewer, thank you for asking, and of course! Assigning to you now.
