### ISSUE TITLE
Doc: How we grant/revoke maintainer status

### ISSUE THREAD

**Issue by gwaybio** [cytomining/pycytominer#328]
### File location of the documentation

https://github.com/cytomining/pycytominer/blob/main/CONTRIBUTING.md

### Documentation issue

We need to define our process for determining maintainer status, both granting and revoking.

### Suggested solution

@d33bs - can you link the maintainer guide we had discussed as an exemplar? I can't seem to find it. We can use this as a inspiration guide.

**Comment by d33bs** [comment]
@gwaybio - sure thing, here are a few guides which might inspire towards this:

- [Opensource.guide - Best Practices - Share the workload](https://opensource.guide/best-practices/#share-the-workload)
- [Opensource.guide - Building Community - Share the ownership of your project](https://opensource.guide/building-community/#share-ownership-of-your-project)
-  [Python Core Developer - Commit privileges](https://devguide.python.org/core-developers/become-core-developer/index.html)
