### ISSUE TITLE
Version 1 release

### ISSUE THREAD

**Issue by gwaybio** [cytomining/pycytominer#330]
We are ready for a version 1 release.

It would be nice to have this release prior to the SBI2 conference (Oct 30).

The release would involve:

1. PR bumping the project build to v1
2. Minting a release which should be built automatically
3. This process should automatically trigger a pypi publication through out [workflow](https://github.com/cytomining/pycytominer/blob/main/.github/workflows/publish-to-pypi.yml) but we should confirm
4. Manually add to conda-forge

It would be great to also add a PR describing our process in the CONTRIBUTING.md guidelines.

**Comment by gwaybio** [comment]
@kenibrewer - I'd like to assign you to this, if you're available and interested. Please let @d33bs and I know if you will not be able to release v1 prior to Oct 30. Thanks!

**Comment by kenibrewer** [comment]
@gwaybio I'll be happy to take this on and get it done by Oct. 30th

**Comment by kenibrewer** [comment]
@gwaybio @d33bs v1.0.0 is successfully released to PyPi. 🚀

How do we get it updated on conda too?

**Comment by gwaybio** [comment]
Woooo! Thanks Ken! Exciting to see this release 🚀 

We need to update https://github.com/conda-forge/pycytominer-feedstock. It looks like a bot automatically created a pull request which is currently failing to build. Are you able to give this a look? Thanks!

**Comment by kenibrewer** [comment]
Sure. Thing. I'll figure it out.

**Comment by kenibrewer** [comment]
Sorted everything with the conda-forge build process so we can close this issue.
