### ISSUE TITLE
Question: Using the package for JUMP-CP postprocessing

### ISSUE THREAD

**Issue by ethancohen123** [cytomining/pycytominer#361]
### Confirmation

- [X] I can confirm that this question/issue does not fall under any of the existing three issue types currently available.

### General question or description

I was wondering if you have any guidelines regarding using this package for the JUMP-CP postprocessing especially regarding the control alignement. Is alignement by plates enough ? Or performing supplementary alignement by batch or source is also necessary ?

**Comment by gwaybio** [comment]
Thanks for raising this issue @ethancohen123 !

I recommend that you refer to the [JUMP-CP resources](https://jump-cellpainting.broadinstitute.org/results) to find answers to your questions. This resource also includes a pointer to the [pycytominer processing steps](https://github.com/jump-cellpainting/2023_Chandrasekaran_submitted?tab=readme-ov-file#step-3-process-the-profiles-using-pycytominer) used in production. You can also take a look at the [JUMP preprint](https://www.biorxiv.org/content/10.1101/2023.03.23.534023v1.full) for experimental design discussions.

You should be able to find your answers there. While Pycytominer provides reasonable defaults and all the tools to process these data, details of the exact pipeline and processing decisions are up to the users :) We'd love to hear back from you regarding some decisions you've made along the way to improve the pipeline. Thanks!
