### ISSUE TITLE
Add `mypy` type check linting

### ISSUE THREAD

**Issue by d33bs** [cytomining/pycytominer#437]
Type hints can oftentimes provide helpful static analysis and developer understanding for project maintenance. We could add `mypy` as a pre-commit check to help ensure changes reach a certain standard.

**Comment by kenibrewer** [comment]
I like `mypy` checking in github actions but typically not precommit hooks because of the long runtime. Would be glad to see us move towards typed python though!

**Comment by d33bs** [comment]
Thanks Ken, good point! Do you have any feelings about Mypy alternatives? I was looking at https://mtshiba.github.io/pylyzer/ just now and wondered if that'd be fast enough to run through pre-commit. Generally I like having the checks prior to CI to help with development iterations, but completely agree that Mypy is relatively slow to run (and also sometimes difficult to decipher).

**Comment by kenibrewer** [comment]
pylyzer looks super exciting! But it's not [ feature-complete enough](https://mtshiba.github.io/pylyzer/#todos) to use as mypy alternative with pydantic in the mix. The `TypedDict`, `TypeAlias` and `Annotated` types are pretty important for that. I'd suggest we start with `mypy` and plan on switching to `pylyzer` once it's more feature complete.
