### ISSUE TITLE
Increase test coverage for `collate`

### ISSUE THREAD

**Issue by d33bs** [cytomining/pycytominer#442]
In working through #437 via #439 I noticed that collate has `collate` has much lower test coverage than other components within pycytominer. We could increase this coverage with some further tests, possibly while also addressing #315 and #394 .

**Comment by gwaybio** [comment]
Yes, we could, in theory increase coverage. See https://github.com/cytomining/pycytominer/pull/160#pullrequestreview-985473258 for our initial discussion of code coverage for `collate`

Given the march toward 2.0, which won't support collate, I'm not sure if it's a wise time investment to increase coverage at this time. Also, there have been no complaints about this functionality not working to my knowledge.

Also, we deprecated `cytominer-database` last week. https://github.com/cytomining/cytominer-database

**Comment by d33bs** [comment]
Closing this issue as no action is necessary.
