### ISSUE TITLE
Parity between pycytominer 1.0 and cytominer

### ISSUE THREAD

**Issue by niranjchandrasekaran** [cytomining/pycytominer#94]
With the imminent release of pycytominer 1.0, @gwaygenomics has been cleaning up some the pycytominer repo and removing some evaluation functions (https://github.com/cytomining/pycytominer/pull/92) that will be moved to the cytominer-eval repo (https://github.com/cytomining/cytominer-eval/issues/3#issuecomment-674232584). 

Though splitting the repository into two (pycytominer for profile processing scripts and cytominer-eval for evaluation scripts) is logical and shouldn't majorly affect any profiling workflows, I was wondering if this decision to split is relevant in the context of how pycytominer 1.0 will be advertised upon release.

- Would pycytominer 1.0 be the python version of the latest [cytominer release](https://github.com/cytomining/cytominer/releases/tag/v0.2.2), in which case, it maybe beneficial to keep the evaluation functions in pycytominer 1.0 so that it doesn't break the parity between pycytominer and cytominer.

- Or can pycytominer 1.0 be considered to have sufficiently diverged from cytominer that it longer matters whether there is parity in functionality (as @gwaygenomics said on slack, it can be argued that an earlier hash of pycytominer should still have the evaluation functionalities)?

**Comment by gwaygenomics** [comment]
from our internal discussions today, we will move forward without the need for parity between pycytominer and cytominer. Our rationale was that requiring this parity slows progress in one tool vs. the other.

We will continue using cytominer in internal assay dev projects, but we will not restrict ourselves in developing the python version.

Going to consider this issue resolved for now, but we can feel free to reopen if new info comes our way
