### ISSUE TITLE
CSV sniff other compression

### ISSUE THREAD

**Issue by gwaybio** [cytomining/pycytominer#99]
In #95 I noted that gzip files will fail `infer_delim()`. #98 made this fix.

However, the fix was limited to `gzip` file compression. We should support all of the compression options that pandas includes:

| compression | fixed |
| :-----------: | :----: |
| .gz | ✅  |
| .bz2 | ❌  |
| .zip | ❌  |
| .xz | ❌  |

from https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html

**Comment by jenna-tomkinson** [comment]
@gwaybio 

Would this issue now extend to all of these file compression types seen below from the most recent documentation?

> For on-the-fly compression of the output data. If ‘infer’ and ‘path_or_buf’ is path-like, then detect compression from the following extensions: ‘.gz’, ‘.bz2’, ‘.zip’, ‘.xz’, ‘.zst’, ‘.tar’, ‘.tar.gz’, ‘.tar.xz’ or ‘.tar.bz2’

**Comment by gwaybio** [comment]
Maybe! We'll likely also have to specify pandas version, if we support these other compressions.

Given there hasn't been any need for other compression algorithms here, we can close this and reopen if this becomes needed.
